// LOCAL HOST //

###
GET http://localhost:3000
###
GET http://localhost:3000/names
###
GET http://localhost:3000/names/test
###
GET http://localhost:3000/contacts
###
GET http://localhost:3000/contacts/63c4d9514acd17fd60937bf2
###
GET http://localhost:3000/contacts/63c4d9514acd17fd60937bf3
###
GET http://localhost:3000/contacts/63c4d9514acd17fd60937bf4

// CREATE CONTACT
###
POST http://localhost:3000/contacts
content-type: application/json

{
"firstName":"Carl", 
"lastName":"McDonald",
"email":"carlMc@gmail.com",
"favoriteColor":"purple",
"birthday":"01/09/1983"
}

// UPDATE CONTACT
###
PUT  http://localhost:3000/contacts/63ccd082b3fcc85a81469291
content-type: application/json

{
"firstName":"Carl", 
"lastName":"McDonald",
"email":"carlMcDonald@gmail.com",
"favoriteColor":"green",
"birthday":"01/09/1983"
}

// DELETE CONTACT BY ID
###
DELETE http://localhost:3000/contacts/63ccd082b3fcc85a81469291


// *** PRODUCTION DEPLOY *** //

###
GET https://cse-341-donnovan.onrender.com
###
GET https://cse-341-donnovan.onrender.com/names
###
GET https://cse-341-donnovan.onrender.com/names/test
###
GET https://cse-341-donnovan.onrender.com/contacts
###
GET https://cse-341-donnovan.onrender.com/contacts/63c4d9514acd17fd60937bf2
###
GET https://cse-341-donnovan.onrender.com/contacts/63c4d9514acd17fd60937bf3
###
GET https://cse-341-donnovan.onrender.com/contacts/63c4d9514acd17fd60937bf4


// CREATE CONTACT
###
POST https://cse-341-donnovan.onrender.com/contacts
content-type: application/json

{
"firstName":"Carl", 
"lastName":"McDonald",
"email":"carlMc@gmail.com",
"favoriteColor":"purple",
"birthday":"01/09/1983"
}

// UPDATE CONTACT
###
PUT  https://cse-341-donnovan.onrender.com/contacts/63ccc7eb1f499a29fb315abf
content-type: application/json

{
"firstName":"Carl", 
"lastName":"McDonald",
"email":"carlMcDonald@gmail.com",
"favoriteColor":"green",
"birthday":"01/09/1983"
}

// DELETE CONTACT BY ID
###
DELETE https://cse-341-donnovan.onrender.com/contacts/63cccd0fd44fa5dd474c902e